name: Update Trello on PR update

on:
  pull_request:
    types:
      - edited
      - opened
      - closed

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        TICKET_NUMBER=$(echo "$PR_TITLE" | tr '[:lower:]' '[:upper:]' | sed -n 's/.*\(\[PS-[0-9]*\]\).*/\1/p')

        STATUS="Doing"
        if [ "${{ github.event.pull_request.state }}" = "closed" ]; then
          STATUS="${{ github.event.pull_request.merged && 'Done' || 'Deleted' }}"
        fi
        bin/change_card_status.sh "$TICKET_NUMBER" "$STATUS"
      env:
        APIKey: ${{ secrets.TRELLO_API_KEY }}
        APIToken: ${{ secrets.TRELLO_API_TOKEN }}
        BoardID: ${{ secrets.TRELLO_BOARD_ID }}
