name: Update Trello on 

on:
  pull_request:
    types: [edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        TICKET_NUMBER=$(echo "$PR_TITLE" | sed -n 's/.*\(\[PS-[0-9]*\]\).*/\1/p')
        bin/change_card_status.sh "$TICKET_NUMBER" "Doing"
