name: Update Trello on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  open_url:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        LATEST_COMMIT_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}")
        LATEST_COMMIT_MESSAGE=$(echo "$LATEST_COMMIT_JSON" | jq -r '.commit.message')
        TICKET_NUMBER=$(echo "$LATEST_COMMIT_MESSAGE" | sed -n 's/.*\(\[PS-[0-9]*\]\).*/\1/p')
        bin/change_card_status.sh "$TICKET_NUMBER" "Done"
